config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :list

end

app/models/list.rb
class List < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :colors, dependent: :destroy
  has_one_attached :image
  
  
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    # 以下score追記(language)
    @list.score = Language.get_data(list_params[:body])
    # 以下tag部分追記(vision)
    base64_image = Vision.get_base64_image(list_params[:image])
    tags = Vision.get_image_data(base64_image)
    colors = Vision.analyze_image(base64_image)
    if @list.save
      # 投稿した画像を Vision.get_image_data(list_params[:image]) でAPI側に渡し、そこから返ってきた値をもとに、タグを作成しています。
      tags.each do |tag|
        @list.tags.create(name: tag)
      end
      @list.colors.create(colors)
      # # 色解析用の追記
      # analyze_image(@list.image) if @list.image.attached?
      
      # analyze_imageメソッド(画像解析)を実行。analyze_imageメソッドはモデルに定義。
      # uploaded_image_path = params[:list][:image].tempfile.path
      redirect_to todolist_path(@list.id)
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to todolists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :body, :image)
  end

  def analyze_image(image)
    # Convert ActiveStorage::Blob to a file path
    image_path = Rails.application.routes.url_helpers.rails_blob_path(image, only_path: true)
    # For cloud storage, you might need to download the file or use the signed URL.
    detect_labels(image_path)
  end

  def detect_labels(image_url)
    vision = Google::Cloud::Vision.image_annotator
    response = vision.label_detection image: image_url
    response.responses.each do |res|
      res.label_annotations.each do |label|
        Rails.logger.info "Label: #{label.description}, Score: #{label.score}"
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleAppDemoApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  <body>
    <header>
      <h1 class="headline"> All Lists </h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "TodoLists", todolists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", todolists_new_path %>
        </li>
      </ul>
    </nav>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
<% end %>

app/views/todolists/index.html.erb
<div class="list-wrap">
<% @lists.each do |list| %>
  <div class="list-box">
    <% if list.image.attached? %>
      <%= image_tag list.image.variant(resize:'200x200') %>
    <% end %>
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
      <!--本文の点数を表示するby language追加-->
      <span class="sentiment-score">本文の感情分析スコア<%= list.score %></span>
      <span class="list-title"><%=link_to list.title, todolist_path(list.id) %></span>
    </div>
  </div>
<% end %>
</div>

app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @list, url:'/todolists', local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <h4>画像</h4>
  <%= f.file_field :image %>
  <%= f.submit '投稿' %>
<% end %>

app/views/todolists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<!--language導入、以下増枠-->
<p class="sentiment-score">本文の感情分析スコア[<%= @list.score %>]</p>
<h2>画像</h2>
<% if @list.image.attached? %>
  <%= image_tag @list.image.variant(resize:'300x300') %>
<% end %>
<div class="tag-box">
<% @list.tags.each do |tag| %>
  <span class="label"><%= tag.name %></span>
<% end %>
<!--<div>【解析した画像】</div>-->
<!-- <%# if @list.image %>-->
<!--   <%#= image_tag @list.image %> -->
<!-- <%# end %>-->

<h5>【画像解析結果のcolor情報】</h5> 
  <%# @list.colors.each do |color| %>
    <%#= color.red %>
    <%#= color.green %>
    <%#= color.blue %>
    <%#= color.score %>
    <!--<div id="colorBox" class="color-sample"></div>-->
  <%# end %>
  <!--JavaScriptで特定の要素を操作する場合には、id ではなく class-->
<% @list.colors.each_with_index do |color, index| %>
  <div class="colorBox" 
       data-red="<%= color.red %>" 
       data-green="<%= color.green %>" 
       data-blue="<%= color.blue %>">
    <p>RGB: <%= color.red %>, <%= color.green %>, <%= color.blue %></p>
    <p>Score: <%= color.score %></p>
  </div>
<% end %>
<!--each_with_index は、Ruby の配列やその他の Enumerable オブジェクトで利用できるメソッドです。
このメソッドは、配列の各要素とその要素のインデックス（位置）をブロックに渡して処理を行います。-->
<!--index は、配列内での要素の位置を示す番号で、0から始まります。-->


  
</div>
<%= link_to "削除", destroy_todolist_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<%= link_to "編集", edit_todolist_path(@list.id) %>

<script src="/js/script.js"></script>